spring:
  datasource:
    url: jdbc:h2:mem:danske
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2.console.enabled: true
server.port: 8080